version: '3.8'

services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: chat-assistant-db
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: 4NEU0UIMu1yTa7JqqXwc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: chat-assistant-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chat-assistant-db
      SPRING_DATASOURCE_USERNAME: backend
      SPRING_DATASOURCE_PASSWORD: 4NEU0UIMu1yTa7JqqXwc

volumes:
  postgres-data: