version: '3.8'

services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: chat-assistant-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_KEY: ${OPENAI_KEY}

volumes:
  postgres-data: